export type customerType  = [{
  active: boolean
  renewsAt: string
  arr: number
  logoUrl: any
  confidence: number
  statusId: number
  id: number
  updatedAt: string
  createdAt: string
  updatedBy: number
  createdBy: number
  name: string
  seats: number
  type: any
  activeAt: string
  confidenceAt: any
  logoFileId: number
  customfieldExamplefield: string
  customfieldSalesforceID: string
  customfieldTheGreatestField: number
  healthCalculatedAt: number
  healthFeedback: number
  healthRawFeedback: number
  healthSeatUtilization: number
  healthSeatUtilizationPercentage: number
  healthSeenAt: number
  healthStartAt: number
  healthSupport: number
  healthSupportDelayed: number
  healthSupportOpen: number
  healthSupportTotal: number
  healthUsageAvg30: number
  healthUsageAvg60: number
  healthRawUsageAvg30: number
  healthRawUsageAvg60: number
  healthHealthDays: number
  healthActiveUsers: number
  healthUsage30ProductA: number
  healthUsage60ProductA: number
  healthRawUsage30ProductA: number
  healthRawUsage60ProductA: number
  healthUsage30ProductB: number
  healthUsage60ProductB: number
  healthRawUsage30ProductB: number
  healthRawUsage60ProductB: number
  healthUsage30ProductC: number
  healthUsage60ProductC: number
  healthRawUsage30ProductC: number
  healthRawUsage60ProductC: number
  healthUsage30Test: number
  healthUsage60Test: number
  healthRawUsage30Test: number
  healthRawUsage60Test: number
  teamMemberId: number[]
  productId: number[]
  tag: any[]
}]